In [3]:
import torch

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"#不设置只显示最后一个变量(不print的话)

x=torch.arange(0,12)

print(x)
x.shape

x.numel()

x.reshape(3,4)




tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [4]:
torch.zeros(1,2,3)


tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [5]:
torch.tensor([[2,1,3,4],[1,2,3,4],[1,2,4,3]])

tensor([[2, 1, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 4, 3]])

In [6]:
torch.tensor([1,2,3,4],dtype=torch.int64)#设置为64位整数
torch.tensor([1.0,2,3,4])#浮点

tensor([1, 2, 3, 4])

tensor([1., 2., 3., 4.])

In [7]:
a=torch.arange(3).reshape(3,1)#广播机制
b=torch.arange(2).reshape(1,2)
a
b
a+b

tensor([[0],
        [1],
        [2]])

tensor([[0, 1]])

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [8]:
X=torch.arange(1,10).reshape(3,3)
Y=torch.arange(6,15).reshape(3,3)

before=id(Y)
Y=Y+X
id(Y)==before

#下面几种方式比较省内存

Z=torch.zeros_like(Y)
before=id(Z)
Z[:]=X+Y
id(Z)==before

before=id(Y)
Y[:]=Y+X
id(Y)==before

before=id(Y)
Y+=X
id(Y)==before

False

True

True

True

In [15]:
import numpy #与numpy互相转换
A=X.numpy()
B=torch.tensor(A)
print(type(A),type(B))


<class 'numpy.ndarray'> <class 'torch.Tensor'>


In [17]:
a=torch.tensor([3.5])
a,a.item(),float(a),int(a)#转换为标量

(tensor([3.5000]), 3.5, 3.5, 3)